/*
 * Price Monitoring Service
 * Price Monitoring Service
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {User} from './User';

/**
 * The Login model module.
 * @module model/Login
 * @version 0.0.1
 */
export class Login {
  /**
   * Constructs a new <code>Login</code>.
   * @alias module:model/Login
   * @class
   * @param refresh {String} 
   * @param access {String} 
   * @param email {String} 
   * @param password {String} 
   */
  constructor(refresh, access, email, password) {
    this.refresh = refresh;
    this.access = access;
    this.email = email;
    this.password = password;
  }

  /**
   * Constructs a <code>Login</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Login} obj Optional instance to populate.
   * @return {module:model/Login} The populated <code>Login</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Login();
      if (data.hasOwnProperty('refresh'))
        obj.refresh = ApiClient.convertToType(data['refresh'], 'String');
      if (data.hasOwnProperty('access'))
        obj.access = ApiClient.convertToType(data['access'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = User.constructFromObject(data['user']);
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} refresh
 */
Login.prototype.refresh = undefined;

/**
 * @member {String} access
 */
Login.prototype.access = undefined;

/**
 * @member {module:model/User} user
 */
Login.prototype.user = undefined;

/**
 * @member {String} email
 */
Login.prototype.email = undefined;

/**
 * @member {String} password
 */
Login.prototype.password = undefined;

