/*
 * Price Monitoring Service
 * Price Monitoring Service
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PatchedTrackItemHeader model module.
 * @module model/PatchedTrackItemHeader
 * @version 0.0.1
 */
export class PatchedTrackItemHeader {
  /**
   * Constructs a new <code>PatchedTrackItemHeader</code>.
   * @alias module:model/PatchedTrackItemHeader
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PatchedTrackItemHeader</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PatchedTrackItemHeader} obj Optional instance to populate.
   * @return {module:model/PatchedTrackItemHeader} The populated <code>PatchedTrackItemHeader</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PatchedTrackItemHeader();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = ApiClient.convertToType(data['user'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
PatchedTrackItemHeader.prototype.name = undefined;

/**
 * @member {String} description
 */
PatchedTrackItemHeader.prototype.description = undefined;

/**
 * @member {Number} user
 */
PatchedTrackItemHeader.prototype.user = undefined;

