/*
 * Price Monitoring Service
 * Price Monitoring Service
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Register model module.
 * @module model/Register
 * @version 0.0.1
 */
export class Register {
  /**
   * Constructs a new <code>Register</code>.
   * @alias module:model/Register
   * @class
   * @param id {Number} 
   * @param username {String} 
   * @param email {String} 
   * @param password {String} 
   * @param created {Date} 
   * @param updated {Date} 
   */
  constructor(id, username, email, password, created, updated) {
    this.id = id;
    this.username = username;
    this.email = email;
    this.password = password;
    this.created = created;
    this.updated = updated;
  }

  /**
   * Constructs a <code>Register</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Register} obj Optional instance to populate.
   * @return {module:model/Register} The populated <code>Register</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Register();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('is_active'))
        obj.isActive = ApiClient.convertToType(data['is_active'], 'Boolean');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Register.prototype.id = undefined;

/**
 * @member {String} username
 */
Register.prototype.username = undefined;

/**
 * @member {String} email
 */
Register.prototype.email = undefined;

/**
 * @member {String} password
 */
Register.prototype.password = undefined;

/**
 * @member {Boolean} isActive
 */
Register.prototype.isActive = undefined;

/**
 * @member {Date} created
 */
Register.prototype.created = undefined;

/**
 * @member {Date} updated
 */
Register.prototype.updated = undefined;

