/*
 * Price Monitoring Service
 * Price Monitoring Service
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {User} from './User';

/**
 * The Register model module.
 * @module model/Register
 * @version 0.0.1
 */
export class Register {
  /**
   * Constructs a new <code>Register</code>.
   * @alias module:model/Register
   * @class
   * @param password {String} 
   * @param username {String} 
   * @param email {String} 
   * @param refresh {String} 
   * @param token {String} 
   */
  constructor(password, username, email, refresh, token) {
    this.password = password;
    this.username = username;
    this.email = email;
    this.refresh = refresh;
    this.token = token;
  }

  /**
   * Constructs a <code>Register</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Register} obj Optional instance to populate.
   * @return {module:model/Register} The populated <code>Register</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Register();
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('refresh'))
        obj.refresh = ApiClient.convertToType(data['refresh'], 'String');
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = User.constructFromObject(data['user']);
    }
    return obj;
  }
}

/**
 * @member {String} password
 */
Register.prototype.password = undefined;

/**
 * @member {String} username
 */
Register.prototype.username = undefined;

/**
 * @member {String} email
 */
Register.prototype.email = undefined;

/**
 * @member {String} refresh
 */
Register.prototype.refresh = undefined;

/**
 * @member {String} token
 */
Register.prototype.token = undefined;

/**
 * @member {module:model/User} user
 */
Register.prototype.user = undefined;

