/*
 * Price Monitoring Service
 * Price Monitoring Service
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TokenRefresh model module.
 * @module model/TokenRefresh
 * @version 0.0.1
 */
export class TokenRefresh {
  /**
   * Constructs a new <code>TokenRefresh</code>.
   * @alias module:model/TokenRefresh
   * @class
   * @param access {String} 
   * @param refresh {String} 
   */
  constructor(access, refresh) {
    this.access = access;
    this.refresh = refresh;
  }

  /**
   * Constructs a <code>TokenRefresh</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TokenRefresh} obj Optional instance to populate.
   * @return {module:model/TokenRefresh} The populated <code>TokenRefresh</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TokenRefresh();
      if (data.hasOwnProperty('access'))
        obj.access = ApiClient.convertToType(data['access'], 'String');
      if (data.hasOwnProperty('refresh'))
        obj.refresh = ApiClient.convertToType(data['refresh'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} access
 */
TokenRefresh.prototype.access = undefined;

/**
 * @member {String} refresh
 */
TokenRefresh.prototype.refresh = undefined;

