/*
 * Price Monitoring Service
 * Price Monitoring Service
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TrackItemHeader model module.
 * @module model/TrackItemHeader
 * @version 0.0.1
 */
export class TrackItemHeader {
  /**
   * Constructs a new <code>TrackItemHeader</code>.
   * @alias module:model/TrackItemHeader
   * @class
   * @param name {String} 
   * @param description {String} 
   * @param user {Number} 
   */
  constructor(name, description, user) {
    this.name = name;
    this.description = description;
    this.user = user;
  }

  /**
   * Constructs a <code>TrackItemHeader</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrackItemHeader} obj Optional instance to populate.
   * @return {module:model/TrackItemHeader} The populated <code>TrackItemHeader</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TrackItemHeader();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('user'))
        obj.user = ApiClient.convertToType(data['user'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
TrackItemHeader.prototype.name = undefined;

/**
 * @member {String} description
 */
TrackItemHeader.prototype.description = undefined;

/**
 * @member {Number} user
 */
TrackItemHeader.prototype.user = undefined;

