/*
 * Price Monitoring Service
 * Price Monitoring Service
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PriceMonitoringService);
  }
}(this, function(expect, PriceMonitoringService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PriceMonitoringService.AuthApi();
  });

  describe('(package)', function() {
    describe('AuthApi', function() {
      describe('authLoginCreate', function() {
        it('should call authLoginCreate successfully', function(done) {
          // TODO: uncomment, update parameter values for authLoginCreate call and complete the assertions
          /*

          instance.authLoginCreate(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PriceMonitoringService.Login);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('authRefreshCreate', function() {
        it('should call authRefreshCreate successfully', function(done) {
          // TODO: uncomment, update parameter values for authRefreshCreate call and complete the assertions
          /*

          instance.authRefreshCreate(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PriceMonitoringService.TokenRefresh);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('authRegisterCreate', function() {
        it('should call authRegisterCreate successfully', function(done) {
          // TODO: uncomment, update parameter values for authRegisterCreate call and complete the assertions
          /*

          instance.authRegisterCreate(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(PriceMonitoringService.Register);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
